CREATE USER 'repusr'@'10.10.1.0/24' IDENTIFIED BY 'REPUSRMYQLP';
GRANT REPLICATION SLAVE, REPLICATION_SLAVE_ADMIN, SUPER, REPLICATION CLIENT ON *.* TO 'repusr'@'10.10.1.0/24'; 
FLUSH PRIVILEGES;
flush logs;
exit;
